# Copyright 1999 DUMPLETON SOFTWARE CONSULTING PTY LIMITED

# Makeit Initialisation.

MODULES := c cc ose

include makeit/init.mk

# Module Initialisation/Definitions.

PROGRAMS += simple-threading
PROGRAMS += agent-threading

include makeit/modules.mk

# Additional Dependencies/Rules.

