$(MK)/otccvmutex.d $(MK).pic/otccvmutex$(OBJEXT) $(MK)/otccvmutex$(OBJEXT) : ../../../config/$(OSE_TARGET)/OSE-CONFIG.h
$(MK)/otccvmutex.d $(MK).pic/otccvmutex$(OBJEXT) $(MK)/otccvmutex$(OBJEXT) : ../../../include/OSE-VERSION.h
$(MK)/otccvmutex.d $(MK).pic/otccvmutex$(OBJEXT) $(MK)/otccvmutex$(OBJEXT) : ../../../include/OSE/OSE.h
$(MK)/otccvmutex.d $(MK).pic/otccvmutex$(OBJEXT) $(MK)/otccvmutex$(OBJEXT) : ../../../include/OTC/misc/types.h
$(MK)/otccvmutex.d $(MK).pic/otccvmutex$(OBJEXT) $(MK)/otccvmutex$(OBJEXT) : ../../../include/OTC/thread/cvmutex.hh
$(MK)/otccvmutex.d $(MK).pic/otccvmutex$(OBJEXT) $(MK)/otccvmutex$(OBJEXT) : ../../../include/OTC/thread/nrmutex.hh
$(MK)/otccvmutex.d $(MK).pic/otccvmutex$(OBJEXT) $(MK)/otccvmutex$(OBJEXT) : ../../../include/OTC/thread/thread.hh
$(MK)/otccvmutex.d $(MK).pic/otccvmutex$(OBJEXT) $(MK)/otccvmutex$(OBJEXT) : otccvmutex.cc
$(MK)/otcmutex.d $(MK).pic/otcmutex$(OBJEXT) $(MK)/otcmutex$(OBJEXT) : ../../../config/$(OSE_TARGET)/OSE-CONFIG.h
$(MK)/otcmutex.d $(MK).pic/otcmutex$(OBJEXT) $(MK)/otcmutex$(OBJEXT) : ../../../include/OSE-VERSION.h
$(MK)/otcmutex.d $(MK).pic/otcmutex$(OBJEXT) $(MK)/otcmutex$(OBJEXT) : ../../../include/OSE/OSE.h
$(MK)/otcmutex.d $(MK).pic/otcmutex$(OBJEXT) $(MK)/otcmutex$(OBJEXT) : ../../../include/OTC/thread/mutex.hh
$(MK)/otcmutex.d $(MK).pic/otcmutex$(OBJEXT) $(MK)/otcmutex$(OBJEXT) : ../../../include/OTC/thread/thread.hh
$(MK)/otcmutex.d $(MK).pic/otcmutex$(OBJEXT) $(MK)/otcmutex$(OBJEXT) : otcmutex.cc
$(MK)/otcnrmutex.d $(MK).pic/otcnrmutex$(OBJEXT) $(MK)/otcnrmutex$(OBJEXT) : ../../../config/$(OSE_TARGET)/OSE-CONFIG.h
$(MK)/otcnrmutex.d $(MK).pic/otcnrmutex$(OBJEXT) $(MK)/otcnrmutex$(OBJEXT) : ../../../include/OSE-VERSION.h
$(MK)/otcnrmutex.d $(MK).pic/otcnrmutex$(OBJEXT) $(MK)/otcnrmutex$(OBJEXT) : ../../../include/OSE/OSE.h
$(MK)/otcnrmutex.d $(MK).pic/otcnrmutex$(OBJEXT) $(MK)/otcnrmutex$(OBJEXT) : ../../../include/OTC/thread/nrmutex.hh
$(MK)/otcnrmutex.d $(MK).pic/otcnrmutex$(OBJEXT) $(MK)/otcnrmutex$(OBJEXT) : ../../../include/OTC/thread/thread.hh
$(MK)/otcnrmutex.d $(MK).pic/otcnrmutex$(OBJEXT) $(MK)/otcnrmutex$(OBJEXT) : otcnrmutex.cc
$(MK)/otcrwmutex.d $(MK).pic/otcrwmutex$(OBJEXT) $(MK)/otcrwmutex$(OBJEXT) : ../../../config/$(OSE_TARGET)/OSE-CONFIG.h
$(MK)/otcrwmutex.d $(MK).pic/otcrwmutex$(OBJEXT) $(MK)/otcrwmutex$(OBJEXT) : ../../../include/OSE-VERSION.h
$(MK)/otcrwmutex.d $(MK).pic/otcrwmutex$(OBJEXT) $(MK)/otcrwmutex$(OBJEXT) : ../../../include/OSE/OSE.h
$(MK)/otcrwmutex.d $(MK).pic/otcrwmutex$(OBJEXT) $(MK)/otcrwmutex$(OBJEXT) : ../../../include/OTC/misc/types.h
$(MK)/otcrwmutex.d $(MK).pic/otcrwmutex$(OBJEXT) $(MK)/otcrwmutex$(OBJEXT) : ../../../include/OTC/thread/cvmutex.hh
$(MK)/otcrwmutex.d $(MK).pic/otcrwmutex$(OBJEXT) $(MK)/otcrwmutex$(OBJEXT) : ../../../include/OTC/thread/nrmutex.hh
$(MK)/otcrwmutex.d $(MK).pic/otcrwmutex$(OBJEXT) $(MK)/otcrwmutex$(OBJEXT) : ../../../include/OTC/thread/rwmutex.hh
$(MK)/otcrwmutex.d $(MK).pic/otcrwmutex$(OBJEXT) $(MK)/otcrwmutex$(OBJEXT) : ../../../include/OTC/thread/thread.hh
$(MK)/otcrwmutex.d $(MK).pic/otcrwmutex$(OBJEXT) $(MK)/otcrwmutex$(OBJEXT) : otcrwmutex.cc
$(MK)/_atomic.d $(MK)/_atomic$(OBJEXT) $(MK)/_atomic$(BINEXT) : ../../../config/$(OSE_TARGET)/OSE-CONFIG.h
$(MK)/_atomic.d $(MK)/_atomic$(OBJEXT) $(MK)/_atomic$(BINEXT) : ../../../include/OSE-VERSION.h
$(MK)/_atomic.d $(MK)/_atomic$(OBJEXT) $(MK)/_atomic$(BINEXT) : ../../../include/OSE/OSE.h
$(MK)/_atomic.d $(MK)/_atomic$(OBJEXT) $(MK)/_atomic$(BINEXT) : ../../../include/OTC/stdlib/iostream.h
$(MK)/_atomic.d $(MK)/_atomic$(OBJEXT) $(MK)/_atomic$(BINEXT) : ../../../include/OTC/thread/atomic.hh
$(MK)/_atomic.d $(MK)/_atomic$(OBJEXT) $(MK)/_atomic$(BINEXT) : ../../../include/OTC/thread/nrmutex.hh
$(MK)/_atomic.d $(MK)/_atomic$(OBJEXT) $(MK)/_atomic$(BINEXT) : ../../../include/OTC/thread/thread.hh
$(MK)/_atomic.d $(MK)/_atomic$(OBJEXT) $(MK)/_atomic$(BINEXT) : _atomic.cc
