$(MK)/otcqtqueue.d $(MK).pic/otcqtqueue$(OBJEXT) $(MK)/otcqtqueue$(OBJEXT) : ../../../config/$(OSE_TARGET)/OSE-CONFIG.h
$(MK)/otcqtqueue.d $(MK).pic/otcqtqueue$(OBJEXT) $(MK)/otcqtqueue$(OBJEXT) : ../../../include/OSE-VERSION.h
$(MK)/otcqtqueue.d $(MK).pic/otcqtqueue$(OBJEXT) $(MK)/otcqtqueue$(OBJEXT) : ../../../include/OSE/OSE.h
$(MK)/otcqtqueue.d $(MK).pic/otcqtqueue$(OBJEXT) $(MK)/otcqtqueue$(OBJEXT) : ../../../include/OTC/OTC.h
$(MK)/otcqtqueue.d $(MK).pic/otcqtqueue$(OBJEXT) $(MK)/otcqtqueue$(OBJEXT) : ../../../include/OTC/collctn/anchor.hh
$(MK)/otcqtqueue.d $(MK).pic/otcqtqueue$(OBJEXT) $(MK)/otcqtqueue$(OBJEXT) : ../../../include/OTC/collctn/applcatr.hh
$(MK)/otcqtqueue.d $(MK).pic/otcqtqueue$(OBJEXT) $(MK)/otcqtqueue$(OBJEXT) : ../../../include/OTC/collctn/baseactn.hh
$(MK)/otcqtqueue.d $(MK).pic/otcqtqueue$(OBJEXT) $(MK)/otcqtqueue$(OBJEXT) : ../../../include/OTC/collctn/cbitset.hh
$(MK)/otcqtqueue.d $(MK).pic/otcqtqueue$(OBJEXT) $(MK)/otcqtqueue$(OBJEXT) : ../../../include/OTC/collctn/copyactn.hh
$(MK)/otcqtqueue.d $(MK).pic/otcqtqueue$(OBJEXT) $(MK)/otcqtqueue$(OBJEXT) : ../../../include/OTC/collctn/cursor.hh
$(MK)/otcqtqueue.d $(MK).pic/otcqtqueue$(OBJEXT) $(MK)/otcqtqueue$(OBJEXT) : ../../../include/OTC/collctn/dirction.hh
$(MK)/otcqtqueue.d $(MK).pic/otcqtqueue$(OBJEXT) $(MK)/otcqtqueue$(OBJEXT) : ../../../include/OTC/collctn/hashactn.hh
$(MK)/otcqtqueue.d $(MK).pic/otcqtqueue$(OBJEXT) $(MK)/otcqtqueue$(OBJEXT) : ../../../include/OTC/collctn/hashntry.hh
$(MK)/otcqtqueue.d $(MK).pic/otcqtqueue$(OBJEXT) $(MK)/otcqtqueue$(OBJEXT) : ../../../include/OTC/collctn/hashtble.hh
$(MK)/otcqtqueue.d $(MK).pic/otcqtqueue$(OBJEXT) $(MK)/otcqtqueue$(OBJEXT) : ../../../include/OTC/collctn/hindex.hh
$(MK)/otcqtqueue.d $(MK).pic/otcqtqueue$(OBJEXT) $(MK)/otcqtqueue$(OBJEXT) : ../../../include/OTC/collctn/hindexen.hh
$(MK)/otcqtqueue.d $(MK).pic/otcqtqueue$(OBJEXT) $(MK)/otcqtqueue$(OBJEXT) : ../../../include/OTC/collctn/hmap.hh
$(MK)/otcqtqueue.d $(MK).pic/otcqtqueue$(OBJEXT) $(MK)/otcqtqueue$(OBJEXT) : ../../../include/OTC/collctn/iterator.hh
$(MK)/otcqtqueue.d $(MK).pic/otcqtqueue$(OBJEXT) $(MK)/otcqtqueue$(OBJEXT) : ../../../include/OTC/collctn/link.hh
$(MK)/otcqtqueue.d $(MK).pic/otcqtqueue$(OBJEXT) $(MK)/otcqtqueue$(OBJEXT) : ../../../include/OTC/collctn/linkable.hh
$(MK)/otcqtqueue.d $(MK).pic/otcqtqueue$(OBJEXT) $(MK)/otcqtqueue$(OBJEXT) : ../../../include/OTC/collctn/linkiter.hh
$(MK)/otcqtqueue.d $(MK).pic/otcqtqueue$(OBJEXT) $(MK)/otcqtqueue$(OBJEXT) : ../../../include/OTC/collctn/linklist.hh
$(MK)/otcqtqueue.d $(MK).pic/otcqtqueue$(OBJEXT) $(MK)/otcqtqueue$(OBJEXT) : ../../../include/OTC/collctn/modifier.hh
$(MK)/otcqtqueue.d $(MK).pic/otcqtqueue$(OBJEXT) $(MK)/otcqtqueue$(OBJEXT) : ../../../include/OTC/collctn/prcursor.hh
$(MK)/otcqtqueue.d $(MK).pic/otcqtqueue$(OBJEXT) $(MK)/otcqtqueue$(OBJEXT) : ../../../include/OTC/collctn/pritertr.hh
$(MK)/otcqtqueue.d $(MK).pic/otcqtqueue$(OBJEXT) $(MK)/otcqtqueue$(OBJEXT) : ../../../include/OTC/collctn/prmodifr.hh
$(MK)/otcqtqueue.d $(MK).pic/otcqtqueue$(OBJEXT) $(MK)/otcqtqueue$(OBJEXT) : ../../../include/OTC/collctn/progress.hh
$(MK)/otcqtqueue.d $(MK).pic/otcqtqueue$(OBJEXT) $(MK)/otcqtqueue$(OBJEXT) : ../../../include/OTC/collctn/prtction.hh
$(MK)/otcqtqueue.d $(MK).pic/otcqtqueue$(OBJEXT) $(MK)/otcqtqueue$(OBJEXT) : ../../../include/OTC/collctn/prvisitr.hh
$(MK)/otcqtqueue.d $(MK).pic/otcqtqueue$(OBJEXT) $(MK)/otcqtqueue$(OBJEXT) : ../../../include/OTC/collctn/prworker.hh
$(MK)/otcqtqueue.d $(MK).pic/otcqtqueue$(OBJEXT) $(MK)/otcqtqueue$(OBJEXT) : ../../../include/OTC/collctn/range.hh
$(MK)/otcqtqueue.d $(MK).pic/otcqtqueue$(OBJEXT) $(MK)/otcqtqueue$(OBJEXT) : ../../../include/OTC/collctn/rankactn.hh
$(MK)/otcqtqueue.d $(MK).pic/otcqtqueue$(OBJEXT) $(MK)/otcqtqueue$(OBJEXT) : ../../../include/OTC/collctn/replcmnt.hh
$(MK)/otcqtqueue.d $(MK).pic/otcqtqueue$(OBJEXT) $(MK)/otcqtqueue$(OBJEXT) : ../../../include/OTC/collctn/shlwcopy.hh
$(MK)/otcqtqueue.d $(MK).pic/otcqtqueue$(OBJEXT) $(MK)/otcqtqueue$(OBJEXT) : ../../../include/OTC/collctn/strgactn.hh
$(MK)/otcqtqueue.d $(MK).pic/otcqtqueue$(OBJEXT) $(MK)/otcqtqueue$(OBJEXT) : ../../../include/OTC/collctn/visitor.hh
$(MK)/otcqtqueue.d $(MK).pic/otcqtqueue$(OBJEXT) $(MK)/otcqtqueue$(OBJEXT) : ../../../include/OTC/collctn/vlink.hh
$(MK)/otcqtqueue.d $(MK).pic/otcqtqueue$(OBJEXT) $(MK)/otcqtqueue$(OBJEXT) : ../../../include/OTC/collctn/worker.hh
$(MK)/otcqtqueue.d $(MK).pic/otcqtqueue$(OBJEXT) $(MK)/otcqtqueue$(OBJEXT) : ../../../include/OTC/debug/assert.h
$(MK)/otcqtqueue.d $(MK).pic/otcqtqueue$(OBJEXT) $(MK)/otcqtqueue$(OBJEXT) : ../../../include/OTC/debug/ensure.h
$(MK)/otcqtqueue.d $(MK).pic/otcqtqueue$(OBJEXT) $(MK)/otcqtqueue$(OBJEXT) : ../../../include/OTC/debug/errors.h
$(MK)/otcqtqueue.d $(MK).pic/otcqtqueue$(OBJEXT) $(MK)/otcqtqueue$(OBJEXT) : ../../../include/OTC/debug/excption.hh
$(MK)/otcqtqueue.d $(MK).pic/otcqtqueue$(OBJEXT) $(MK)/otcqtqueue$(OBJEXT) : ../../../include/OTC/debug/newhndlr.hh
$(MK)/otcqtqueue.d $(MK).pic/otcqtqueue$(OBJEXT) $(MK)/otcqtqueue$(OBJEXT) : ../../../include/OTC/debug/stophere.h
$(MK)/otcqtqueue.d $(MK).pic/otcqtqueue$(OBJEXT) $(MK)/otcqtqueue$(OBJEXT) : ../../../include/OTC/debug/taginfo.hh
$(MK)/otcqtqueue.d $(MK).pic/otcqtqueue$(OBJEXT) $(MK)/otcqtqueue$(OBJEXT) : ../../../include/OTC/debug/termfunc.hh
$(MK)/otcqtqueue.d $(MK).pic/otcqtqueue$(OBJEXT) $(MK)/otcqtqueue$(OBJEXT) : ../../../include/OTC/debug/throwerr.hh
$(MK)/otcqtqueue.d $(MK).pic/otcqtqueue$(OBJEXT) $(MK)/otcqtqueue$(OBJEXT) : ../../../include/OTC/debug/tracer.hh
$(MK)/otcqtqueue.d $(MK).pic/otcqtqueue$(OBJEXT) $(MK)/otcqtqueue$(OBJEXT) : ../../../include/OTC/debug/tracetag.hh
$(MK)/otcqtqueue.d $(MK).pic/otcqtqueue$(OBJEXT) $(MK)/otcqtqueue$(OBJEXT) : ../../../include/OTC/debug/trcebuf.hh
$(MK)/otcqtqueue.d $(MK).pic/otcqtqueue$(OBJEXT) $(MK)/otcqtqueue$(OBJEXT) : ../../../include/OTC/debug/trcestrm.hh
$(MK)/otcqtqueue.d $(MK).pic/otcqtqueue$(OBJEXT) $(MK)/otcqtqueue$(OBJEXT) : ../../../include/OTC/debug/trcswtch.hh
$(MK)/otcqtqueue.d $(MK).pic/otcqtqueue$(OBJEXT) $(MK)/otcqtqueue$(OBJEXT) : ../../../include/OTC/debug/warning.h
$(MK)/otcqtqueue.d $(MK).pic/otcqtqueue$(OBJEXT) $(MK)/otcqtqueue$(OBJEXT) : ../../../include/OTC/dispatch/alarm.hh
$(MK)/otcqtqueue.d $(MK).pic/otcqtqueue$(OBJEXT) $(MK)/otcqtqueue$(OBJEXT) : ../../../include/OTC/dispatch/condtion.hh
$(MK)/otcqtqueue.d $(MK).pic/otcqtqueue$(OBJEXT) $(MK)/otcqtqueue$(OBJEXT) : ../../../include/OTC/dispatch/dispatch.hh
$(MK)/otcqtqueue.d $(MK).pic/otcqtqueue$(OBJEXT) $(MK)/otcqtqueue$(OBJEXT) : ../../../include/OTC/dispatch/event.hh
$(MK)/otcqtqueue.d $(MK).pic/otcqtqueue$(OBJEXT) $(MK)/otcqtqueue$(OBJEXT) : ../../../include/OTC/dispatch/ioevent.hh
$(MK)/otcqtqueue.d $(MK).pic/otcqtqueue$(OBJEXT) $(MK)/otcqtqueue$(OBJEXT) : ../../../include/OTC/dispatch/job.hh
$(MK)/otcqtqueue.d $(MK).pic/otcqtqueue$(OBJEXT) $(MK)/otcqtqueue$(OBJEXT) : ../../../include/OTC/dispatch/joblist.hh
$(MK)/otcqtqueue.d $(MK).pic/otcqtqueue$(OBJEXT) $(MK)/otcqtqueue$(OBJEXT) : ../../../include/OTC/dispatch/jobqueue.hh
$(MK)/otcqtqueue.d $(MK).pic/otcqtqueue$(OBJEXT) $(MK)/otcqtqueue$(OBJEXT) : ../../../include/OTC/dispatch/receiver.hh
$(MK)/otcqtqueue.d $(MK).pic/otcqtqueue$(OBJEXT) $(MK)/otcqtqueue$(OBJEXT) : ../../../include/OTC/dispatch/signal.hh
$(MK)/otcqtqueue.d $(MK).pic/otcqtqueue$(OBJEXT) $(MK)/otcqtqueue$(OBJEXT) : ../../../include/OTC/dispatch/timeout.hh
$(MK)/otcqtqueue.d $(MK).pic/otcqtqueue$(OBJEXT) $(MK)/otcqtqueue$(OBJEXT) : ../../../include/OTC/memory/cmmnpool.hh
$(MK)/otcqtqueue.d $(MK).pic/otcqtqueue$(OBJEXT) $(MK)/otcqtqueue$(OBJEXT) : ../../../include/OTC/memory/mpobject.hh
$(MK)/otcqtqueue.d $(MK).pic/otcqtqueue$(OBJEXT) $(MK)/otcqtqueue$(OBJEXT) : ../../../include/OTC/memory/pool.hh
$(MK)/otcqtqueue.d $(MK).pic/otcqtqueue$(OBJEXT) $(MK)/otcqtqueue$(OBJEXT) : ../../../include/OTC/misc/ascii.h
$(MK)/otcqtqueue.d $(MK).pic/otcqtqueue$(OBJEXT) $(MK)/otcqtqueue$(OBJEXT) : ../../../include/OTC/misc/bool.h
$(MK)/otcqtqueue.d $(MK).pic/otcqtqueue$(OBJEXT) $(MK)/otcqtqueue$(OBJEXT) : ../../../include/OTC/misc/copy.hh
$(MK)/otcqtqueue.d $(MK).pic/otcqtqueue$(OBJEXT) $(MK)/otcqtqueue$(OBJEXT) : ../../../include/OTC/misc/funcbuf.hh
$(MK)/otcqtqueue.d $(MK).pic/otcqtqueue$(OBJEXT) $(MK)/otcqtqueue$(OBJEXT) : ../../../include/OTC/misc/funcstrm.hh
$(MK)/otcqtqueue.d $(MK).pic/otcqtqueue$(OBJEXT) $(MK)/otcqtqueue$(OBJEXT) : ../../../include/OTC/misc/hash.hh
$(MK)/otcqtqueue.d $(MK).pic/otcqtqueue$(OBJEXT) $(MK)/otcqtqueue$(OBJEXT) : ../../../include/OTC/misc/limits.h
$(MK)/otcqtqueue.d $(MK).pic/otcqtqueue$(OBJEXT) $(MK)/otcqtqueue$(OBJEXT) : ../../../include/OTC/misc/macros.h
$(MK)/otcqtqueue.d $(MK).pic/otcqtqueue$(OBJEXT) $(MK)/otcqtqueue$(OBJEXT) : ../../../include/OTC/misc/rank.hh
$(MK)/otcqtqueue.d $(MK).pic/otcqtqueue$(OBJEXT) $(MK)/otcqtqueue$(OBJEXT) : ../../../include/OTC/misc/termnate.hh
$(MK)/otcqtqueue.d $(MK).pic/otcqtqueue$(OBJEXT) $(MK)/otcqtqueue$(OBJEXT) : ../../../include/OTC/misc/types.h
$(MK)/otcqtqueue.d $(MK).pic/otcqtqueue$(OBJEXT) $(MK)/otcqtqueue$(OBJEXT) : ../../../include/OTC/ostore/locality.hh
$(MK)/otcqtqueue.d $(MK).pic/otcqtqueue$(OBJEXT) $(MK)/otcqtqueue$(OBJEXT) : ../../../include/OTC/ostore/ostore.hh
$(MK)/otcqtqueue.d $(MK).pic/otcqtqueue$(OBJEXT) $(MK)/otcqtqueue$(OBJEXT) : ../../../include/OTC/ostore/typespec.hh
$(MK)/otcqtqueue.d $(MK).pic/otcqtqueue$(OBJEXT) $(MK)/otcqtqueue$(OBJEXT) : ../../../include/OTC/qt/qtqueue.hh
$(MK)/otcqtqueue.d $(MK).pic/otcqtqueue$(OBJEXT) $(MK)/otcqtqueue$(OBJEXT) : ../../../include/OTC/refcnt/count.hh
$(MK)/otcqtqueue.d $(MK).pic/otcqtqueue$(OBJEXT) $(MK)/otcqtqueue$(OBJEXT) : ../../../include/OTC/refcnt/resource.hh
$(MK)/otcqtqueue.d $(MK).pic/otcqtqueue$(OBJEXT) $(MK)/otcqtqueue$(OBJEXT) : ../../../include/OTC/stdlib/iomanip.h
$(MK)/otcqtqueue.d $(MK).pic/otcqtqueue$(OBJEXT) $(MK)/otcqtqueue$(OBJEXT) : ../../../include/OTC/stdlib/iostream.h
$(MK)/otcqtqueue.d $(MK).pic/otcqtqueue$(OBJEXT) $(MK)/otcqtqueue$(OBJEXT) : ../../../include/OTC/text/cstring.hh
$(MK)/otcqtqueue.d $(MK).pic/otcqtqueue$(OBJEXT) $(MK)/otcqtqueue$(OBJEXT) : ../../../include/OTC/text/rstring.hh
$(MK)/otcqtqueue.d $(MK).pic/otcqtqueue$(OBJEXT) $(MK)/otcqtqueue$(OBJEXT) : ../../../include/OTC/text/sobject.hh
$(MK)/otcqtqueue.d $(MK).pic/otcqtqueue$(OBJEXT) $(MK)/otcqtqueue$(OBJEXT) : ../../../include/OTC/text/string.hh
$(MK)/otcqtqueue.d $(MK).pic/otcqtqueue$(OBJEXT) $(MK)/otcqtqueue$(OBJEXT) : ../../../include/OTC/text/tstring.hh
$(MK)/otcqtqueue.d $(MK).pic/otcqtqueue$(OBJEXT) $(MK)/otcqtqueue$(OBJEXT) : ../../../include/OTC/thread/mutex.hh
$(MK)/otcqtqueue.d $(MK).pic/otcqtqueue$(OBJEXT) $(MK)/otcqtqueue$(OBJEXT) : ../../../include/OTC/thread/mxreaper.hh
$(MK)/otcqtqueue.d $(MK).pic/otcqtqueue$(OBJEXT) $(MK)/otcqtqueue$(OBJEXT) : ../../../include/OTC/thread/nrmutex.hh
$(MK)/otcqtqueue.d $(MK).pic/otcqtqueue$(OBJEXT) $(MK)/otcqtqueue$(OBJEXT) : ../../../include/OTC/thread/thread.hh
$(MK)/otcqtqueue.d $(MK).pic/otcqtqueue$(OBJEXT) $(MK)/otcqtqueue$(OBJEXT) : otcqtqueue.cc
$(MK)/moc_qtqueue.d $(MK).pic/moc_qtqueue$(OBJEXT) $(MK)/moc_qtqueue$(OBJEXT) : ../../../config/$(OSE_TARGET)/OSE-CONFIG.h
$(MK)/moc_qtqueue.d $(MK).pic/moc_qtqueue$(OBJEXT) $(MK)/moc_qtqueue$(OBJEXT) : ../../../include/OSE-VERSION.h
$(MK)/moc_qtqueue.d $(MK).pic/moc_qtqueue$(OBJEXT) $(MK)/moc_qtqueue$(OBJEXT) : ../../../include/OSE/OSE.h
$(MK)/moc_qtqueue.d $(MK).pic/moc_qtqueue$(OBJEXT) $(MK)/moc_qtqueue$(OBJEXT) : ../../../include/OTC/OTC.h
$(MK)/moc_qtqueue.d $(MK).pic/moc_qtqueue$(OBJEXT) $(MK)/moc_qtqueue$(OBJEXT) : ../../../include/OTC/collctn/anchor.hh
$(MK)/moc_qtqueue.d $(MK).pic/moc_qtqueue$(OBJEXT) $(MK)/moc_qtqueue$(OBJEXT) : ../../../include/OTC/collctn/applcatr.hh
$(MK)/moc_qtqueue.d $(MK).pic/moc_qtqueue$(OBJEXT) $(MK)/moc_qtqueue$(OBJEXT) : ../../../include/OTC/collctn/copyactn.hh
$(MK)/moc_qtqueue.d $(MK).pic/moc_qtqueue$(OBJEXT) $(MK)/moc_qtqueue$(OBJEXT) : ../../../include/OTC/collctn/cursor.hh
$(MK)/moc_qtqueue.d $(MK).pic/moc_qtqueue$(OBJEXT) $(MK)/moc_qtqueue$(OBJEXT) : ../../../include/OTC/collctn/dirction.hh
$(MK)/moc_qtqueue.d $(MK).pic/moc_qtqueue$(OBJEXT) $(MK)/moc_qtqueue$(OBJEXT) : ../../../include/OTC/collctn/hashactn.hh
$(MK)/moc_qtqueue.d $(MK).pic/moc_qtqueue$(OBJEXT) $(MK)/moc_qtqueue$(OBJEXT) : ../../../include/OTC/collctn/hashntry.hh
$(MK)/moc_qtqueue.d $(MK).pic/moc_qtqueue$(OBJEXT) $(MK)/moc_qtqueue$(OBJEXT) : ../../../include/OTC/collctn/hashtble.hh
$(MK)/moc_qtqueue.d $(MK).pic/moc_qtqueue$(OBJEXT) $(MK)/moc_qtqueue$(OBJEXT) : ../../../include/OTC/collctn/hmap.hh
$(MK)/moc_qtqueue.d $(MK).pic/moc_qtqueue$(OBJEXT) $(MK)/moc_qtqueue$(OBJEXT) : ../../../include/OTC/collctn/iterator.hh
$(MK)/moc_qtqueue.d $(MK).pic/moc_qtqueue$(OBJEXT) $(MK)/moc_qtqueue$(OBJEXT) : ../../../include/OTC/collctn/link.hh
$(MK)/moc_qtqueue.d $(MK).pic/moc_qtqueue$(OBJEXT) $(MK)/moc_qtqueue$(OBJEXT) : ../../../include/OTC/collctn/linkable.hh
$(MK)/moc_qtqueue.d $(MK).pic/moc_qtqueue$(OBJEXT) $(MK)/moc_qtqueue$(OBJEXT) : ../../../include/OTC/collctn/linkiter.hh
$(MK)/moc_qtqueue.d $(MK).pic/moc_qtqueue$(OBJEXT) $(MK)/moc_qtqueue$(OBJEXT) : ../../../include/OTC/collctn/linklist.hh
$(MK)/moc_qtqueue.d $(MK).pic/moc_qtqueue$(OBJEXT) $(MK)/moc_qtqueue$(OBJEXT) : ../../../include/OTC/collctn/modifier.hh
$(MK)/moc_qtqueue.d $(MK).pic/moc_qtqueue$(OBJEXT) $(MK)/moc_qtqueue$(OBJEXT) : ../../../include/OTC/collctn/prcursor.hh
$(MK)/moc_qtqueue.d $(MK).pic/moc_qtqueue$(OBJEXT) $(MK)/moc_qtqueue$(OBJEXT) : ../../../include/OTC/collctn/pritertr.hh
$(MK)/moc_qtqueue.d $(MK).pic/moc_qtqueue$(OBJEXT) $(MK)/moc_qtqueue$(OBJEXT) : ../../../include/OTC/collctn/prmodifr.hh
$(MK)/moc_qtqueue.d $(MK).pic/moc_qtqueue$(OBJEXT) $(MK)/moc_qtqueue$(OBJEXT) : ../../../include/OTC/collctn/progress.hh
$(MK)/moc_qtqueue.d $(MK).pic/moc_qtqueue$(OBJEXT) $(MK)/moc_qtqueue$(OBJEXT) : ../../../include/OTC/collctn/prtction.hh
$(MK)/moc_qtqueue.d $(MK).pic/moc_qtqueue$(OBJEXT) $(MK)/moc_qtqueue$(OBJEXT) : ../../../include/OTC/collctn/prvisitr.hh
$(MK)/moc_qtqueue.d $(MK).pic/moc_qtqueue$(OBJEXT) $(MK)/moc_qtqueue$(OBJEXT) : ../../../include/OTC/collctn/prworker.hh
$(MK)/moc_qtqueue.d $(MK).pic/moc_qtqueue$(OBJEXT) $(MK)/moc_qtqueue$(OBJEXT) : ../../../include/OTC/collctn/rankactn.hh
$(MK)/moc_qtqueue.d $(MK).pic/moc_qtqueue$(OBJEXT) $(MK)/moc_qtqueue$(OBJEXT) : ../../../include/OTC/collctn/replcmnt.hh
$(MK)/moc_qtqueue.d $(MK).pic/moc_qtqueue$(OBJEXT) $(MK)/moc_qtqueue$(OBJEXT) : ../../../include/OTC/collctn/shlwcopy.hh
$(MK)/moc_qtqueue.d $(MK).pic/moc_qtqueue$(OBJEXT) $(MK)/moc_qtqueue$(OBJEXT) : ../../../include/OTC/collctn/strgactn.hh
$(MK)/moc_qtqueue.d $(MK).pic/moc_qtqueue$(OBJEXT) $(MK)/moc_qtqueue$(OBJEXT) : ../../../include/OTC/collctn/visitor.hh
$(MK)/moc_qtqueue.d $(MK).pic/moc_qtqueue$(OBJEXT) $(MK)/moc_qtqueue$(OBJEXT) : ../../../include/OTC/collctn/vlink.hh
$(MK)/moc_qtqueue.d $(MK).pic/moc_qtqueue$(OBJEXT) $(MK)/moc_qtqueue$(OBJEXT) : ../../../include/OTC/collctn/worker.hh
$(MK)/moc_qtqueue.d $(MK).pic/moc_qtqueue$(OBJEXT) $(MK)/moc_qtqueue$(OBJEXT) : ../../../include/OTC/debug/assert.h
$(MK)/moc_qtqueue.d $(MK).pic/moc_qtqueue$(OBJEXT) $(MK)/moc_qtqueue$(OBJEXT) : ../../../include/OTC/debug/ensure.h
$(MK)/moc_qtqueue.d $(MK).pic/moc_qtqueue$(OBJEXT) $(MK)/moc_qtqueue$(OBJEXT) : ../../../include/OTC/debug/errors.h
$(MK)/moc_qtqueue.d $(MK).pic/moc_qtqueue$(OBJEXT) $(MK)/moc_qtqueue$(OBJEXT) : ../../../include/OTC/debug/excption.hh
$(MK)/moc_qtqueue.d $(MK).pic/moc_qtqueue$(OBJEXT) $(MK)/moc_qtqueue$(OBJEXT) : ../../../include/OTC/debug/newhndlr.hh
$(MK)/moc_qtqueue.d $(MK).pic/moc_qtqueue$(OBJEXT) $(MK)/moc_qtqueue$(OBJEXT) : ../../../include/OTC/debug/stophere.h
$(MK)/moc_qtqueue.d $(MK).pic/moc_qtqueue$(OBJEXT) $(MK)/moc_qtqueue$(OBJEXT) : ../../../include/OTC/debug/termfunc.hh
$(MK)/moc_qtqueue.d $(MK).pic/moc_qtqueue$(OBJEXT) $(MK)/moc_qtqueue$(OBJEXT) : ../../../include/OTC/debug/throwerr.hh
$(MK)/moc_qtqueue.d $(MK).pic/moc_qtqueue$(OBJEXT) $(MK)/moc_qtqueue$(OBJEXT) : ../../../include/OTC/debug/warning.h
$(MK)/moc_qtqueue.d $(MK).pic/moc_qtqueue$(OBJEXT) $(MK)/moc_qtqueue$(OBJEXT) : ../../../include/OTC/dispatch/condtion.hh
$(MK)/moc_qtqueue.d $(MK).pic/moc_qtqueue$(OBJEXT) $(MK)/moc_qtqueue$(OBJEXT) : ../../../include/OTC/dispatch/job.hh
$(MK)/moc_qtqueue.d $(MK).pic/moc_qtqueue$(OBJEXT) $(MK)/moc_qtqueue$(OBJEXT) : ../../../include/OTC/dispatch/joblist.hh
$(MK)/moc_qtqueue.d $(MK).pic/moc_qtqueue$(OBJEXT) $(MK)/moc_qtqueue$(OBJEXT) : ../../../include/OTC/dispatch/jobqueue.hh
$(MK)/moc_qtqueue.d $(MK).pic/moc_qtqueue$(OBJEXT) $(MK)/moc_qtqueue$(OBJEXT) : ../../../include/OTC/memory/cmmnpool.hh
$(MK)/moc_qtqueue.d $(MK).pic/moc_qtqueue$(OBJEXT) $(MK)/moc_qtqueue$(OBJEXT) : ../../../include/OTC/memory/mpobject.hh
$(MK)/moc_qtqueue.d $(MK).pic/moc_qtqueue$(OBJEXT) $(MK)/moc_qtqueue$(OBJEXT) : ../../../include/OTC/memory/pool.hh
$(MK)/moc_qtqueue.d $(MK).pic/moc_qtqueue$(OBJEXT) $(MK)/moc_qtqueue$(OBJEXT) : ../../../include/OTC/misc/ascii.h
$(MK)/moc_qtqueue.d $(MK).pic/moc_qtqueue$(OBJEXT) $(MK)/moc_qtqueue$(OBJEXT) : ../../../include/OTC/misc/bool.h
$(MK)/moc_qtqueue.d $(MK).pic/moc_qtqueue$(OBJEXT) $(MK)/moc_qtqueue$(OBJEXT) : ../../../include/OTC/misc/copy.hh
$(MK)/moc_qtqueue.d $(MK).pic/moc_qtqueue$(OBJEXT) $(MK)/moc_qtqueue$(OBJEXT) : ../../../include/OTC/misc/hash.hh
$(MK)/moc_qtqueue.d $(MK).pic/moc_qtqueue$(OBJEXT) $(MK)/moc_qtqueue$(OBJEXT) : ../../../include/OTC/misc/limits.h
$(MK)/moc_qtqueue.d $(MK).pic/moc_qtqueue$(OBJEXT) $(MK)/moc_qtqueue$(OBJEXT) : ../../../include/OTC/misc/macros.h
$(MK)/moc_qtqueue.d $(MK).pic/moc_qtqueue$(OBJEXT) $(MK)/moc_qtqueue$(OBJEXT) : ../../../include/OTC/misc/rank.hh
$(MK)/moc_qtqueue.d $(MK).pic/moc_qtqueue$(OBJEXT) $(MK)/moc_qtqueue$(OBJEXT) : ../../../include/OTC/misc/termnate.hh
$(MK)/moc_qtqueue.d $(MK).pic/moc_qtqueue$(OBJEXT) $(MK)/moc_qtqueue$(OBJEXT) : ../../../include/OTC/misc/types.h
$(MK)/moc_qtqueue.d $(MK).pic/moc_qtqueue$(OBJEXT) $(MK)/moc_qtqueue$(OBJEXT) : ../../../include/OTC/ostore/locality.hh
$(MK)/moc_qtqueue.d $(MK).pic/moc_qtqueue$(OBJEXT) $(MK)/moc_qtqueue$(OBJEXT) : ../../../include/OTC/ostore/ostore.hh
$(MK)/moc_qtqueue.d $(MK).pic/moc_qtqueue$(OBJEXT) $(MK)/moc_qtqueue$(OBJEXT) : ../../../include/OTC/ostore/typespec.hh
$(MK)/moc_qtqueue.d $(MK).pic/moc_qtqueue$(OBJEXT) $(MK)/moc_qtqueue$(OBJEXT) : ../../../include/OTC/refcnt/count.hh
$(MK)/moc_qtqueue.d $(MK).pic/moc_qtqueue$(OBJEXT) $(MK)/moc_qtqueue$(OBJEXT) : ../../../include/OTC/refcnt/resource.hh
$(MK)/moc_qtqueue.d $(MK).pic/moc_qtqueue$(OBJEXT) $(MK)/moc_qtqueue$(OBJEXT) : ../../../include/OTC/stdlib/iostream.h
$(MK)/moc_qtqueue.d $(MK).pic/moc_qtqueue$(OBJEXT) $(MK)/moc_qtqueue$(OBJEXT) : ../../../include/OTC/thread/nrmutex.hh
$(MK)/moc_qtqueue.d $(MK).pic/moc_qtqueue$(OBJEXT) $(MK)/moc_qtqueue$(OBJEXT) : ../../../include/OTC/thread/thread.hh
$(MK)/moc_qtqueue.d $(MK).pic/moc_qtqueue$(OBJEXT) $(MK)/moc_qtqueue$(OBJEXT) : $(MK)/../../../../include/OTC/qt/qtqueue.hh
$(MK)/moc_qtqueue.d $(MK).pic/moc_qtqueue$(OBJEXT) $(MK)/moc_qtqueue$(OBJEXT) : $(MK)/moc_qtqueue.cc
