# Copyright 1999-2001 DUMPLETON SOFTWARE CONSULTING PTY LIMITED

# Makeit Initialisation.

MODULES = c cc ose

MAKEIT_OPTIONS = purify

include makeit/init.mk

# Module Initialisation/Definitions.

PROGRAMS += read-client
PROGRAMS += write-client

PROGRAMS += daytime-server
PROGRAMS += echo-server
PROGRAMS += chargen-server

include makeit/modules.mk

# Additional Dependencies/Rules.

