# Copyright 2001 DUMPLETON SOFTWARE CONSULTING PTY LIMITED

# Makeit Initialisation.

MODULES = c cc ose

MAKEIT_OPTIONS = purify

include makeit/init.mk

# Module Initialisation/Definitions.

PROGRAMS += request-reply

PROGRAMS += reply

PROGRAMS += request-uptime
PROGRAMS += request-multiply

PROGRAMS += publish-subscribe

PROGRAMS += exchange
PROGRAMS += exchange-network

PROGRAMS += publish
PROGRAMS += subscribe

PROGRAMS += publish-backend
PROGRAMS += publish-frontend

PROGRAMS += netrpc-gateway

include makeit/modules.mk

# Additional Dependencies/Rules.

