# Copyright 2001 DUMPLETON SOFTWARE CONSULTING PTY LIMITED

# Makeit Initialisation.

MODULES = c cc ose

MAKEIT_OPTIONS = purify

include makeit/init.mk

# Module Initialisation/Definitions.

PROGRAMS += validator-service

include makeit/modules.mk

# Additional Dependencies/Rules.

