$(MK)/otccopy.d $(MK).pic/otccopy$(OBJEXT) $(MK)/otccopy$(OBJEXT) : ../../../config/$(OSE_TARGET)/OSE-CONFIG.h
$(MK)/otccopy.d $(MK).pic/otccopy$(OBJEXT) $(MK)/otccopy$(OBJEXT) : ../../../include/OSE-VERSION.h
$(MK)/otccopy.d $(MK).pic/otccopy$(OBJEXT) $(MK)/otccopy$(OBJEXT) : ../../../include/OSE/OSE.h
$(MK)/otccopy.d $(MK).pic/otccopy$(OBJEXT) $(MK)/otccopy$(OBJEXT) : ../../../include/OTC/misc/copy.hh
$(MK)/otccopy.d $(MK).pic/otccopy$(OBJEXT) $(MK)/otccopy$(OBJEXT) : ../../../include/OTC/misc/types.h
$(MK)/otccopy.d $(MK).pic/otccopy$(OBJEXT) $(MK)/otccopy$(OBJEXT) : otccopy.cc
$(MK)/otcfuncbuf.d $(MK).pic/otcfuncbuf$(OBJEXT) $(MK)/otcfuncbuf$(OBJEXT) : ../../../config/$(OSE_TARGET)/OSE-CONFIG.h
$(MK)/otcfuncbuf.d $(MK).pic/otcfuncbuf$(OBJEXT) $(MK)/otcfuncbuf$(OBJEXT) : ../../../include/OSE-VERSION.h
$(MK)/otcfuncbuf.d $(MK).pic/otcfuncbuf$(OBJEXT) $(MK)/otcfuncbuf$(OBJEXT) : ../../../include/OSE/OSE.h
$(MK)/otcfuncbuf.d $(MK).pic/otcfuncbuf$(OBJEXT) $(MK)/otcfuncbuf$(OBJEXT) : ../../../include/OTC/misc/bufflag.hh
$(MK)/otcfuncbuf.d $(MK).pic/otcfuncbuf$(OBJEXT) $(MK)/otcfuncbuf$(OBJEXT) : ../../../include/OTC/misc/funcbuf.hh
$(MK)/otcfuncbuf.d $(MK).pic/otcfuncbuf$(OBJEXT) $(MK)/otcfuncbuf$(OBJEXT) : ../../../include/OTC/misc/types.h
$(MK)/otcfuncbuf.d $(MK).pic/otcfuncbuf$(OBJEXT) $(MK)/otcfuncbuf$(OBJEXT) : ../../../include/OTC/stdlib/iostream.h
$(MK)/otcfuncbuf.d $(MK).pic/otcfuncbuf$(OBJEXT) $(MK)/otcfuncbuf$(OBJEXT) : otcfuncbuf.cc
$(MK)/otcfuncstrm.d $(MK).pic/otcfuncstrm$(OBJEXT) $(MK)/otcfuncstrm$(OBJEXT) : ../../../config/$(OSE_TARGET)/OSE-CONFIG.h
$(MK)/otcfuncstrm.d $(MK).pic/otcfuncstrm$(OBJEXT) $(MK)/otcfuncstrm$(OBJEXT) : ../../../include/OSE-VERSION.h
$(MK)/otcfuncstrm.d $(MK).pic/otcfuncstrm$(OBJEXT) $(MK)/otcfuncstrm$(OBJEXT) : ../../../include/OSE/OSE.h
$(MK)/otcfuncstrm.d $(MK).pic/otcfuncstrm$(OBJEXT) $(MK)/otcfuncstrm$(OBJEXT) : ../../../include/OTC/misc/bufflag.hh
$(MK)/otcfuncstrm.d $(MK).pic/otcfuncstrm$(OBJEXT) $(MK)/otcfuncstrm$(OBJEXT) : ../../../include/OTC/misc/funcbuf.hh
$(MK)/otcfuncstrm.d $(MK).pic/otcfuncstrm$(OBJEXT) $(MK)/otcfuncstrm$(OBJEXT) : ../../../include/OTC/misc/funcstrm.hh
$(MK)/otcfuncstrm.d $(MK).pic/otcfuncstrm$(OBJEXT) $(MK)/otcfuncstrm$(OBJEXT) : ../../../include/OTC/misc/types.h
$(MK)/otcfuncstrm.d $(MK).pic/otcfuncstrm$(OBJEXT) $(MK)/otcfuncstrm$(OBJEXT) : ../../../include/OTC/stdlib/iostream.h
$(MK)/otcfuncstrm.d $(MK).pic/otcfuncstrm$(OBJEXT) $(MK)/otcfuncstrm$(OBJEXT) : otcfuncstrm.cc
$(MK)/otchash.d $(MK).pic/otchash$(OBJEXT) $(MK)/otchash$(OBJEXT) : ../../../config/$(OSE_TARGET)/OSE-CONFIG.h
$(MK)/otchash.d $(MK).pic/otchash$(OBJEXT) $(MK)/otchash$(OBJEXT) : ../../../include/OSE-VERSION.h
$(MK)/otchash.d $(MK).pic/otchash$(OBJEXT) $(MK)/otchash$(OBJEXT) : ../../../include/OSE/OSE.h
$(MK)/otchash.d $(MK).pic/otchash$(OBJEXT) $(MK)/otchash$(OBJEXT) : ../../../include/OTC/misc/hash.hh
$(MK)/otchash.d $(MK).pic/otchash$(OBJEXT) $(MK)/otchash$(OBJEXT) : ../../../include/OTC/misc/types.h
$(MK)/otchash.d $(MK).pic/otchash$(OBJEXT) $(MK)/otchash$(OBJEXT) : otchash.cc
$(MK)/otcrank.d $(MK).pic/otcrank$(OBJEXT) $(MK)/otcrank$(OBJEXT) : ../../../config/$(OSE_TARGET)/OSE-CONFIG.h
$(MK)/otcrank.d $(MK).pic/otcrank$(OBJEXT) $(MK)/otcrank$(OBJEXT) : ../../../include/OSE-VERSION.h
$(MK)/otcrank.d $(MK).pic/otcrank$(OBJEXT) $(MK)/otcrank$(OBJEXT) : ../../../include/OSE/OSE.h
$(MK)/otcrank.d $(MK).pic/otcrank$(OBJEXT) $(MK)/otcrank$(OBJEXT) : ../../../include/OTC/misc/rank.hh
$(MK)/otcrank.d $(MK).pic/otcrank$(OBJEXT) $(MK)/otcrank$(OBJEXT) : ../../../include/OTC/misc/types.h
$(MK)/otcrank.d $(MK).pic/otcrank$(OBJEXT) $(MK)/otcrank$(OBJEXT) : otcrank.cc
$(MK)/otctermnate.d $(MK).pic/otctermnate$(OBJEXT) $(MK)/otctermnate$(OBJEXT) : ../../../include/OTC/misc/termnate.hh
$(MK)/otctermnate.d $(MK).pic/otctermnate$(OBJEXT) $(MK)/otctermnate$(OBJEXT) : otctermnate.cc
$(MK)/otcvfuncbuf.d $(MK).pic/otcvfuncbuf$(OBJEXT) $(MK)/otcvfuncbuf$(OBJEXT) : ../../../config/$(OSE_TARGET)/OSE-CONFIG.h
$(MK)/otcvfuncbuf.d $(MK).pic/otcvfuncbuf$(OBJEXT) $(MK)/otcvfuncbuf$(OBJEXT) : ../../../include/OSE-VERSION.h
$(MK)/otcvfuncbuf.d $(MK).pic/otcvfuncbuf$(OBJEXT) $(MK)/otcvfuncbuf$(OBJEXT) : ../../../include/OSE/OSE.h
$(MK)/otcvfuncbuf.d $(MK).pic/otcvfuncbuf$(OBJEXT) $(MK)/otcvfuncbuf$(OBJEXT) : ../../../include/OTC/misc/bufflag.hh
$(MK)/otcvfuncbuf.d $(MK).pic/otcvfuncbuf$(OBJEXT) $(MK)/otcvfuncbuf$(OBJEXT) : ../../../include/OTC/misc/types.h
$(MK)/otcvfuncbuf.d $(MK).pic/otcvfuncbuf$(OBJEXT) $(MK)/otcvfuncbuf$(OBJEXT) : ../../../include/OTC/misc/vfuncbuf.hh
$(MK)/otcvfuncbuf.d $(MK).pic/otcvfuncbuf$(OBJEXT) $(MK)/otcvfuncbuf$(OBJEXT) : ../../../include/OTC/stdlib/iostream.h
$(MK)/otcvfuncbuf.d $(MK).pic/otcvfuncbuf$(OBJEXT) $(MK)/otcvfuncbuf$(OBJEXT) : otcvfuncbuf.cc
$(MK)/_funcstrm.d $(MK)/_funcstrm$(OBJEXT) $(MK)/_funcstrm$(BINEXT) : ../../../config/$(OSE_TARGET)/OSE-CONFIG.h
$(MK)/_funcstrm.d $(MK)/_funcstrm$(OBJEXT) $(MK)/_funcstrm$(BINEXT) : ../../../include/OSE-VERSION.h
$(MK)/_funcstrm.d $(MK)/_funcstrm$(OBJEXT) $(MK)/_funcstrm$(BINEXT) : ../../../include/OSE/OSE.h
$(MK)/_funcstrm.d $(MK)/_funcstrm$(OBJEXT) $(MK)/_funcstrm$(BINEXT) : ../../../include/OTC/misc/bufflag.hh
$(MK)/_funcstrm.d $(MK)/_funcstrm$(OBJEXT) $(MK)/_funcstrm$(BINEXT) : ../../../include/OTC/misc/funcbuf.hh
$(MK)/_funcstrm.d $(MK)/_funcstrm$(OBJEXT) $(MK)/_funcstrm$(BINEXT) : ../../../include/OTC/misc/funcstrm.hh
$(MK)/_funcstrm.d $(MK)/_funcstrm$(OBJEXT) $(MK)/_funcstrm$(BINEXT) : ../../../include/OTC/misc/types.h
$(MK)/_funcstrm.d $(MK)/_funcstrm$(OBJEXT) $(MK)/_funcstrm$(BINEXT) : ../../../include/OTC/stdlib/iostream.h
$(MK)/_funcstrm.d $(MK)/_funcstrm$(OBJEXT) $(MK)/_funcstrm$(BINEXT) : _funcstrm.cc
$(MK)/_vfuncbuf.d $(MK)/_vfuncbuf$(OBJEXT) $(MK)/_vfuncbuf$(BINEXT) : ../../../config/$(OSE_TARGET)/OSE-CONFIG.h
$(MK)/_vfuncbuf.d $(MK)/_vfuncbuf$(OBJEXT) $(MK)/_vfuncbuf$(BINEXT) : ../../../include/OSE-VERSION.h
$(MK)/_vfuncbuf.d $(MK)/_vfuncbuf$(OBJEXT) $(MK)/_vfuncbuf$(BINEXT) : ../../../include/OSE/OSE.h
$(MK)/_vfuncbuf.d $(MK)/_vfuncbuf$(OBJEXT) $(MK)/_vfuncbuf$(BINEXT) : ../../../include/OTC/misc/bufflag.hh
$(MK)/_vfuncbuf.d $(MK)/_vfuncbuf$(OBJEXT) $(MK)/_vfuncbuf$(BINEXT) : ../../../include/OTC/misc/types.h
$(MK)/_vfuncbuf.d $(MK)/_vfuncbuf$(OBJEXT) $(MK)/_vfuncbuf$(BINEXT) : ../../../include/OTC/misc/vfuncbuf.hh
$(MK)/_vfuncbuf.d $(MK)/_vfuncbuf$(OBJEXT) $(MK)/_vfuncbuf$(BINEXT) : ../../../include/OTC/stdlib/iostream.h
$(MK)/_vfuncbuf.d $(MK)/_vfuncbuf$(OBJEXT) $(MK)/_vfuncbuf$(BINEXT) : _vfuncbuf.cc
